name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-remote:
    runs-on: ubuntu-latest
    steps:

    - name: Execute Ansible Playbook

      uses: saubermacherag/ansible-playbook-docker-action@v1.4
      with:
        playbookName: ".ansible/playbooks/playbook.yml"
