name: Test Action



on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test-remote:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: dawidd6/action-ansible-playbook@v2

        with:
          playbook: playbook.yml
          directory: scripts
