name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-remote:
    runs-on: ubuntu-latest
    steps:

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./
          inventory: |
            [all]
            example.com

            [group1]
            example.com
          options: |
            --limit group1
            --extra-vars hello=there
            --verbose
